from django.db import models
from django.utils import timezone
# Create your models here.


class Person(models.Model):
    IL_CHOICES = (
        ('Adana', 'Adana'),
        ('Adıyaman', 'Adıyaman'),
        ('Afyonkarahisar', 'Afyonkarahisar'),
        ('Ağrı', 'Ağrı'),
        ('Aksaray', 'Aksaray'),
        ('Amasya', 'Amasya'),
        ('Ankara', 'Ankara'),
        ('Antalya', 'Antalya'),
        ('Ardahan', 'Ardahan'),
        ('Artvin', 'Artvin'),
        ('Aydın', 'Aydın'),
        ('Balıkesir', 'Balıkesir'),
        ('Bartın', 'Bartın'),
        ('Batman', 'Batman'),
        ('Bayburt', 'Bayburt'),
        ('Bilecik', 'Bilecik'),
        ('Bingöl', 'Bingöl'),
        ('Bitlis', 'Bitlis'),
        ('Bolu', 'Bolu'),
        ('Burdur', 'Burdur'),
        ('Bursa', 'Bursa'),
        ('Çanakkale', 'Çanakkale'),
        ('Çankırı', 'Çankırı'),
        ('Çorum', 'Çorum'),
        ('Denizli', 'Denizli'),
        ('Diyarbakır', 'Diyarbakır'),
        ('Düzce', 'Düzce'),
        ('Edirne', 'Edirne'),
        ('Elazığ', 'Elazığ'),
        ('Erzincan', 'Erzincan'),
        ('Erzurum', 'Erzurum'),
        ('Eskişehir', 'Eskişehir'),
        ('Gaziantep', 'Gaziantep'),
        ('Giresun', 'Giresun'),
        ('Gümüşhane', 'Gümüşhane'),
        ('Hakkâri', 'Hakkâri'),
        ('Hatay', 'Hatay'),
        ('Iğdır', 'Iğdır'),
        ('Isparta', 'Isparta'),
        ('İstanbul', 'İstanbul'),
        ('İzmir', 'İzmir'),
        ('Kahramanmaraş', 'Kahramanmaraş'),
        ('Karabük', 'Karabük'),
        ('Karaman', 'Karaman'),
        ('Kars', 'Kars'),
        ('Kastamonu', 'Kastamonu'),
        ('Kayseri', 'Kayseri'),
        ('Kırıkkale', 'Kırıkkale'),
        ('Kırklareli', 'Kırklareli'),
        ('Kırşehir', 'Kırşehir'),
        ('Kilis', 'Kilis'),
        ('Kocaeli', 'Kocaeli'),
        ('Konya', 'Konya'),
        ('Kütahya', 'Kütahya'),
        ('Malatya', 'Malatya'),
        ('Manisa', 'Manisa'),
        ('Mardin', 'Mardin'),
        ('Mersin', 'Mersin'),
        ('Muğla', 'Muğla'),
        ('Muş', 'Muş'),
        ('Nevşehir', 'Nevşehir'),
        ('Niğde', 'Niğde'),
        ('Ordu', 'Ordu'),
        ('Osmaniye', 'Osmaniye'),
        ('Rize', 'Rize'),
        ('Sakarya', 'Sakarya'),
        ('Samsun', 'Samsun'),
        ('Siirt', 'Siirt'),
        ('Sinop', 'Sinop'),
        ('Sivas', 'Sivas'),
        ('Şanlıurfa', 'Şanlıurfa'),
        ('Şırnak', 'Şırnak'),
        ('Tekirdağ', 'Tekirdağ'),
        ('Tokat', 'Tokat'),
        ('Trabzon', 'Trabzon'),
        ('Tunceli', 'Tunceli'),
        ('Uşak', 'Uşak'),
        ('Van', 'Van'),
        ('Yalova', 'Yalova'),
        ('Yozgat', 'Yozgat'),
        ('Zonguldak', 'Zonguldak'),
    )

    DURUM_CHOICES = (
        ("iyiyim", "İyiyim"),
        ("yardim", "Enkaz altında değilim fakat yardıma ihtiyacım var"),
        ("enkaz-altinda", "Enkaz altındayım"),
        ("olu", "Ölü"),
        ("hastane-yatis", "Hastane Yatış"),
    )

    isim = models.CharField(max_length=100, unique=True)
    sehir = models.CharField(max_length=100, choices=IL_CHOICES)
    adres = models.CharField(max_length=256)
    notlar = models.CharField(max_length=256, blank=True, null=True)
    tel = models.CharField(max_length=11, default="Yok")
    durum = models.CharField(max_length=100, choices=DURUM_CHOICES)
    created_at = models.DateTimeField(default=timezone.now)
    address = models.IPAddressField()
