# Generated by Django 4.1.6 on 2023-02-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_person_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='tel',
            field=models.CharField(default='Yok', max_length=11),
        ),
    ]
