# Generated by Django 4.1.6 on 2023-02-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_person_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='durum',
            field=models.CharField(choices=[('iyiyim', 'İyiyim'), ('enkaz-altinda', 'Enkaz altında değilim fakat yardıma ihtiyacım var'), ('enkaz-altinda', 'Enkaz altındayım')], max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='sehir',
            field=models.CharField(choices=[('Adana', 'Adana'), ('Batman', 'Batman'), ('Bitlis', 'Bitlis'), ('Bingöl', 'Bingöl'), ('Diyarbakır', 'Diyarbakır'), ('Elazığ', 'Elazığ'), ('Gaziantep', 'Gaziantep'), ('Hakkari', 'Hakkari'), ('Hatay', 'Hatay'), ('Kahramanmaraş', 'Kahramanmaraş'), ('Kilis', 'Kilis'), ('Malatya', 'Malatya'), ('Mardin', 'Mardin'), ('Muş', 'Muş'), ('Osmaniye', 'Osmaniye'), ('Siirt', 'Siirt'), ('Şırnak', 'Şırnak'), ('Van', 'Van')], max_length=100),
        ),
    ]
