# Generated by Django 4.1.6 on 2023-02-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_person_durum_alter_person_sehir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='durum',
            field=models.CharField(choices=[('iyiyim', 'İyiyim'), ('yardim', 'Enkaz altında değilim fakat yardıma ihtiyacım var'), ('enkaz-altinda', 'Enkaz altındayım')], max_length=100),
        ),
    ]
