# Generated by Django 4.1.6 on 2023-02-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_person_isim_alter_person_sehir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='durum',
            field=models.CharField(choices=[('iyiyim', 'İyiyim'), ('yardim', 'Enkaz altında değilim fakat yardıma ihtiyacım var'), ('enkaz-altinda', 'Enkaz altındayım'), ('olu', 'Ölü'), ('hastane-yatis', 'Hastane Yatış')], max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='isim',
            field=models.CharField(max_length=100),
        ),
    ]
