# Generated by Django 4.1.6 on 2023-02-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_person_address_person_notlar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='notlar',
            field=models.CharField(blank=True, default='Yok', max_length=200),
        ),
    ]
